Updated endpoints and certificates to appapi2.
jjabba/php-bankid-base pull request #1
Opened 2019-02-08 14:30 UTC by TwoD

BankID is about to close down the old `appapi` endpoints, so lets switch to the new one.

2019-02-28 08:15 UTC, jjabba requested changes
First and foremost: thanks for taking the time to make this PR!

To enable users to switch their server environments at any given time by means of configuration rather then re-deploy I would prefer if a constant was introduced in the *fixed settings* area to select which API to use: I.e. APIV1 or APIV2. This also means leaving the v1 pem certs in for now, and having some logic added to set default pem files and url based on the api endpoint selection.

2019-03-03 11:23 UTC, TwoD commented
Ok, maybe I can take a look at doing that next week.

Had I had more time I would probably have made this an option from the start, but a notification was sent out by BankID on 8 February stating these changes must be implemented before March.
Having that option available would still mean you'd need to redeploy very soon, so I figured you may just as well switch over at that point.
The notification did also say the old endpoint will stop functioning completely on 1 June but I have not tried using since we made the switch so I can not confirm it is still fully functional.

(We'd need to re-implement parts of this library for the new JSON based API at some point too, but that's a different matter.)

2019-03-04 23:01 UTC, jjabba commented
> Ok, maybe I can take a look at doing that next week.

Sounds good! I'll take a look as soon as you update.

>Having that option available would still mean you'd need to redeploy very soon, so I figured you may just as well switch over at that point.

I would imagine most people would, but as this is a library I wouldn't want a minor version release to enforce that decision on anyone. Instead I want it to be a 2 step process for anyone using this lib:

1. update the library to the latest version (make sure it's still working well with apiv1)
2. add your new production certificates and switch the api version in the lib settings to "apiv2"


I'm no longer working with any PHP project using this, and have no access to production BankID environments, so it's hard for me to maintain this library as far as more elaborate changes goes. Depending on how different the json API is, perhaps that should go into another library entirely?

2020-01-24 23:44 UTC, jjabba approved these changes

2020-01-24 23:44 UTC, merged